// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tUknown-0]
	_ = x[tNumber-1]
	_ = x[tOpPlus-2]
	_ = x[tOpMinus-3]
	_ = x[tOpMultiply-4]
	_ = x[tOpDivide-5]
	_ = x[tOpModulo-6]
	_ = x[tOpPower-7]
	_ = x[tEOF-8]
}

const _TokenType_name = "tUknowntNumbertOpPlustOpMinustOpMultiplytOpDividetOpModulotOpPowertEOF"

var _TokenType_index = [...]uint8{0, 7, 14, 21, 29, 40, 49, 58, 66, 70}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
