#[derive(PartialEq, Clone)]
pub enum NodeKind {
    Program,
    FunctionDefinition,
    FunctionReturn,
    IfStatement,
    ForStatement,
    VariableStatement,
    ExpressionStatement,
    CallStatement,
    ConditionStatement,
    Condition,
    MathStatement,
    StringConcat,
    ParentheseStatement,
    Identifier,
    Array,
    String,
    Number,
    Boolean,
    BMathExpression,
    BStringConcatExpression,
}
